server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: dofus-tools-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.dofustools: INFO
    org.springframework: INFO
